### ISSUE TITLE
method 'fig.subplit_adjust()' should be 'fig.subplots_adjust' in ann.py

### ISSUE THREAD

**Issue by lgyhero** [CanoeFZH/kaggle#1]
Thanks so much for providing your codes. But I see a small error in your 'ann.py' file. The method 'fig.subplit_adjust()' should be 'fig.subplots_adjust'.

**Comment by CanoeFZH** [comment]
haha, thanks for your report. I will fix it.

**Comment by CanoeFZH** [comment]
Or you may send a pull request to me and I will merge it.

**Comment by CanoeFZH** [comment]
@lgyhero
